export const worksPostsData = [
  {
    _id: { $oid: "613649af86634b0016a0abb1" },
    domain: "ml",
    color: "#5129A6",
    github: "https://github.com/sidouxie/instatech-website",
    slug: "instatech",
    colorText: "#c0a5ff",
    colorTitle: "#130B26",
    techno: [
      {
        id: 7,
        stacks: [
          "Html",
          "Scss",
          "Javascript",
          "React Js",
          "Express Js",
          "Redux",
        ],
      },
    ],
    title: "Instatech",
    link: "https://instatech.netlify.app/",
    description:
      "Instatech - un réseau social qui reprend la base d'instagram, développer par mes soins avec tout le backend en express js, mongo db et gérer par un front en react redux. ",
    createdAt: { $date: "2021-09-06T17:02:39.596Z" },
    updatedAt: { $date: "2021-10-17T11:06:52.967Z" },
    __v: 0,
    photo: "instatech-website.webp",
    mockupPhoto: "mock_instatech.png",
  },
  {
    _id: { $oid: "6136450386634b0016a0abae" },
    domain: "ml",
    color: "#015d82",
    github: "https://github.com/sidouxie/Darky-Plumbing",
    slug: "darky-plumbing",
    colorText: "#3ac7e0",
    colorTitle: "#002729",
    techno: [{ id: 6, stacks: ["Html", "Scss", "Javascript", "Next Js"] }],
    title: "Darky-Plumbing",
    link: "https://darky-plumbing.netlify.app",
    description:
      "Plombier chauffagiste Alger. Artisan agréée et spécialisée dans la plomberie, le chauffage et l'assainissement. Riche d'une expérience et de savoir-faire à votre service.",
    createdAt: { $date: "2021-09-06T16:42:43.264Z" },
    updatedAt: { $date: "2021-10-17T11:06:29.515Z" },
    __v: 0,
    photo: "darky-capture.webp",
    mockupPhoto: "mock_darky_plumbing.png",
  },
  {
    _id: { $oid: "6136448686634b0016a0abac" },
    domain: "ml",
    color: "#0033cc",
    github: "https://github.com/sidouxie/droppy",
    slug: "droppy",
    colorText: "#628bfd",
    colorTitle: "#001b6a",
    techno: [
      { id: 5, stacks: ["Html", "Scss", "Javascript", "Next Js", "Graphql"] },
    ],
    title: "Droppy",
    link: "https://droppy.vercel.app",
    description:
      "Droppy - Platforme de streaming français, Retrouvez tout vos filmes, séries, animes préférer en streaming gratuit, illimité et soyez les premiers à voir les derniers épisodes en exclusivité sur Droppy.",
    createdAt: { $date: "2021-09-06T16:40:38.900Z" },
    updatedAt: { $date: "2021-10-17T11:06:04.734Z" },
    __v: 0,
    photo: "droppy-capture.webp",
    mockupPhoto: "mock_droppy.png",
  },
  {
    _id: { $oid: "613643ce86634b0016a0abaa" },
    domain: "ml",
    color: "#1c1c1c",
    github: "https://github.com/sidouxie/willab",
    slug: "walid-khaladi-v2",
    colorText: "#8a8f8b",
    colorTitle: "#A8A8A8",
    techno: [{ id: 4, stacks: ["Html", "Scss", "Javascript", "React Js"] }],
    title: "Walid Khaladi v2",
    link: "https://willab.netlify.app",
    description:
      "Walid Khaladi est un Photographe Professionnel de mode et de célébrités qui réalise des portraits de magazines, des photographies publicitaires basé à Alger.",
    createdAt: { $date: "2021-09-06T16:37:34.002Z" },
    updatedAt: { $date: "2021-10-17T11:05:34.743Z" },
    __v: 0,
    photo: "willab-capture.webp",
    mockupPhoto: "mock_willab.png",
  },
  {
    _id: { $oid: "6136439086634b0016a0aba8" },
    domain: "ml",
    color: "#009898",
    github: "https://github.com/sidouxie/n-seddi",
    slug: "n-seddi",
    colorText: "#45e1e4",
    colorTitle: "#002729",
    techno: [{ id: 3, stacks: ["Html", "Scss", "Javascript", "Next Js"] }],
    title: "N-Seddi",
    link: "https://n-seddi.netlify.app",
    description:
      "N.SEDDI est un commissaire aux comptes comptables agréé à Delly Ibrahim Alger",
    createdAt: { $date: "2021-09-06T16:36:32.618Z" },
    updatedAt: { $date: "2021-10-17T11:05:01.531Z" },
    __v: 0,
    photo: "nseddi-capture.webp",
    mockupPhoto: "mock_n-seddi.png",
  },
  {
    _id: { $oid: "6136433386634b0016a0aba6" },
    domain: "ml",
    color: "#74bac2",
    github: "https://github.com/sidouxie/walidkhaladi",
    slug: "walid-khaladi-v1",
    colorText: "#B3F7FF",
    colorTitle: "#284042",
    techno: [{ id: 2, stacks: ["Html", "Scss", "Javascript", "Gatsby Js"] }],
    title: "Walid Khaladi v1",
    link: "https://walidkhaladi.netlify.app",
    description:
      "Walid Khaladi est un photographe professionnel qui prend des photos de paysages, de la nature et des évènements culturels basés à Alger qui réalise aussi des portraits des élèves primaires, des photographies publicitaires et de mariages.",
    createdAt: { $date: "2021-09-06T16:34:59.931Z" },
    updatedAt: { $date: "2021-10-17T11:04:33.336Z" },
    __v: 0,
    photo: "walid-capture.webp",
    mockupPhoto: "mock_walidkhaladi_v1.png",
  },
  {
    _id: { $oid: "6136425586634b0016a0aba4" },
    domain: "ml",
    color: "#11e783",
    github: "https://github.com/sidouxie/sidouxie-v2",
    slug: "sidouxie-v2",
    colorText: "#0CA85F",
    colorTitle: "#07693B",
    techno: [{ id: 1, stacks: ["Html", "Scss", "Javascript"] }],
    title: "Sidouxie v2",
    link: "https://sidouxie-v2.netlify.app",
    description:
      "Mon premier site portfolio simple et responsif. développer en 2018 c'est là où j'ai appris le scss et le responsif design avec les events listener en Javascript brute.\nÀ ce moment-là je n'avais pas encore d'identité visuelle donc j'ai choisi une couleur aléatoirement et une typographie apple native.",
    createdAt: { $date: "2021-09-06T16:31:17.781Z" },
    updatedAt: { $date: "2021-10-17T11:03:59.264Z" },
    __v: 0,
    photo: "sidouxie-capture.webp",
    mockupPhoto: "mock_sidouxie_v1.png",
  },
];
